name: Install nginx
on:
   push:
      branches: ["main"]

jobs:
   install-ngnix:
     runs-on: ubuntu-latest
      
     steps: 
       - name: Checkout repo
         uses: actions/checkout@v4

       - name: Update Packages
         run: |
           echo "Updating packages..."
           sudo apt-get update -y

       - name: Install ngnix
         run: |
           echo "Starting nginx..."
           sudo systemctl start nginx
           sudo systemctl enable nginx
  
       - name: Verify ngnix status
         run: |
          echo "checking ngnix status..."
          systemctl status ngnix | head -n 10
       - name: Backup nginx
         run: |
           mkdir -p backup
           tar -czvf ~/backup/nginx-config.tar.gz /etc/nginx
           sudo tar -cnz backup/ngnix-html.tar.gz /var/www/html ||  sudo tar -cnz backup/nginx
           ls -lh backup/
